services:
  mysql:
    image: mysql:8.0
    container_name: home-anywhere-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: home_anywhere
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - home-anywhere

networks:
  home-anywhere:
    driver: bridge

volumes:
  mysql_data:
